listen_addresses = '*'
hba_file = '/etc/postgresql/pg_hba.conf'
wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
wal_keep_size = 256MB
logging_collector = on
log_statement = 'all'
